-- TABLE
CREATE TABLE cliente (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, nome VARCHAR(255) NOT NULL, idade INTEGER NOT NULL, cpf VARCHAR(11) NOT NULL, rg VARCHAR(11) NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
